### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by ionutvmi** [Microsoft/IEDiagnosticsAdapter#11] opened 2015-04-04 22:29 UTC
Does it really need to kill the CPU in order to work ?

![cpu](http://puu.sh/h1Fyv/75cc33a361.png)

**Comment by danmosemsft** [comment] 2015-04-05 00:59
No it should barely use the CPU at all. Are you able to identify steps to reproduce this? Or perhaps get a call stack?

**Comment by ionutvmi** [comment] 2015-04-05 06:07
All I did is start the program. There is no extra step.
I'm windows 7 x64

**Comment by praveenpuglia** [comment] 2015-04-06 09:34
On windows 7 x64 I can confirm High CPU Usage. Mine was almost always about 25% or more. Even when not debugging a page.

After couple of observations I saw that it is fixed at 25% no matter what. Strange.

**Comment by alexcope** [comment] 2015-04-20 22:07
This appears to be caused by IEDiagnosticsAdapter::Poll busy waiting, I'm looking into a fix now. @praveenpuglia I'm guessing your machine has four cores, so one busy thread would result in 25% CPU usage.

**Comment by praveenpuglia** [comment] 2015-04-21 02:58
That's right! I have a 4 core system.

**Comment by alexcope** [comment] 2015-04-22 23:51
This issue has been fixed by commit b56a4d0.

**Closed by alexcope** 2015-04-22 23:51 UTC

**Comment by praveenpuglia** [comment] 2015-04-27 17:21
@alexcope should we consider this low? I am on constant 12.5 or more.. ranging between 12.5 - 16% CPU. 
![ie-diagnostics](https://cloud.githubusercontent.com/assets/313363/7353246/d599bbb8-ed2f-11e4-9b68-5cc743797f7a.PNG)

**Comment by alexcope** [comment] 2015-04-29 21:20
Are you running from the released build or building yourself from master? This should be fixed in master, but we have not yet had a release with the fix in it.

**Comment by praveenpuglia** [comment] 2015-04-30 03:00
I am using the released build. I thought it's released. I'll check once in my local build.
